### ISSUE TITLE
Having title score 1

### ISSUE THREAD

**Issue by kmyohan0** [cheolmin711/sentiment_analysis#2]
When running score for articles (including title and subtitle), all articles' titles score as 1. (Can reproduce the same error by typing:

```
for example in articles_lst:
    print(example[0])

```

**Comment by cheolmin711** [comment]
This was happening because the words were capitalized for the titles and the abstracts, so those words were not found from the hash table. Fixed it by lowercasing those strings before splitting them in the tokenizer.
